### ISSUE TITLE
Some tech recommendations

### ISSUE THREAD

**Issue by NG-Joseph** [josh-umahi/wordbanker#2]
- React Query as fetching library + for a bit of state management (The fetch handlers come with hooks that allow you to write logic at different stages of the request lifecycle and on events like success, all built in!). Also comes with states like `isLoading` in built. Finally, it caches the fetch results, so you can avoid double fetching and conditionally invalidate fetches (e.g. when a new entry is added).
- Nextjs: Create-React-App has a lot of [pitfalls](https://www.youtube.com/watch?v=ToEp--KcXcA) + `next/image` for image caching an optimization and better SEO out of the box. Server side rendering 
- Formik: for forms (handles form state a lot better)
- Typescript: Honestly, I think in the long-run it'll make dev time a lot faster.

Great work, man! Lmk what you think and 2 weeks from now I can make PRs if you wish.

**Comment by josh-umahi** [comment]
Thanks a lot bro, I really appreciate the tips.

- I'll definitely consider using React Query in the next version of this app, it totally skipped my mind
- I decided to stick with pure React for the first version of the project just to display some breadth on my portfolio (as I already have a project with NextJS on there)
- Not familiar with Formik but I'll check it out 
- Converting to Typescript sounds like a good idea, will get to it soon

Yes I would love some collaboration! (That Typescript conversion seems like a great place to start : ) but yeah do whatever works best for you! I'm gonna release the README sometime within the next few hours so you can have a better view of the project.

**Comment by NG-Joseph** [comment]
Nice nice. Project defence on Friday. After, I'll start making PRs

**Comment by josh-umahi** [comment]
Great stuff, good luck G
