### ISSUE TITLE
Add React Query

### ISSUE THREAD

**Issue by NG-Joseph** [josh-umahi/wordbanker#6]
Not for state management, but just to cache bulky API responses (Posts, for example). I can tell the site is a bit slow, which is probably a server thing, so caching would be ideal. We can invalidate the cache quietly every 15 seconds, so the user never sees outdated content for too long. We can also implement cool stuff like infinite scroll, and React query would lazily fetch. Goated Library 🐐

**Comment by josh-umahi** [comment]
Looked into React Query yesterday, Like you said it does appear to have a bunch of bonuses. I'll begin implementing it today. Thanks for the suggestion!

**Comment by josh-umahi** [comment]
Implemented React Query 9 days ago in key GET requests as promised, now closing this issue. Will implement in more areas soon as needed.
